<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>daforno-mail-server</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DafornoMail.Core\DafornoMail.Core.csproj" />
    <ProjectReference Include="..\DafornoMail.Infrastructure\DafornoMail.Infrastructure.csproj" />
  </ItemGroup>

</Project>
